Add caching to circumvent ISO re-downloads (currently Ubuntu-only)
After a perfectly good download, why re-download? This pain point
comes up fast and hard once you can create multiple VMs from the same
release/edition.

cached_web_get handles the job of wget, but keeps a cache of
downloaded objects and hard links the ISO image after download so that
it is also present in the expected VM_PATH. As long as everybody is in
the same UNIX filesystem (an apparent quickget assumption, at least at
present), this is a simple and reasonable thing to do: It saves much
time *and* disk space.

The downloaded objects must be uniquely named, but the hash is still
checked after return to get_ubuntu, so hopefully it won't cause harm
when new/different ISOs show up. Time will tell with this
experiment. This function would need some redesign to support multiple
OSes, but ... one step at a time.

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -102,6 +102,33 @@ function validate_release() {
   fi
 }
 
+function cached_web_get {
+    OS="${1}"
+    RELEASE="${2}"
+    URL_ISO="${3}/${4}"
+    VM_PATH="${5}"
+
+    CACHE_DIR=__wget_cache__
+    CACHED_RELEASE_DIR="${CACHE_DIR}/${OS}-${RELEASE}"
+
+    if [ -e "${VM_PATH}" ] ; then
+        echo "ERROR: Already exists: ${VM_PATH}"
+        return 1
+    fi
+    [ -e "${CACHED_RELEASE_DIR}"/"${ISO}" ] && HAVE_CACHED=true || HAVE_CACHED=false
+    if [ ! -d "${RELEASE_DIR}" ] ; then
+        mkdir -p "${RELEASE_DIR}"
+    fi
+    if ! ${HAVE_CACHED} ; then
+        echo "Missing '${CACHED_RELEASE_DIR}/${ISO}', so downloading it into the cache."
+        web_get "${URL_ISO}" "${CACHED_RELEASE_DIR}"
+    fi
+    echo "Creating: ${VM_PATH}"
+    mkdir -p  "${VM_PATH}"
+    ln "${CACHED_RELEASE_DIR}"/"${ISO}"  "${VM_PATH}"/"${ISO}"
+    return $?
+}
+
 function list_json() {
   # Reference: https://stackoverflow.com/a/67359273
   list_csv | jq -R 'split(",") as $h|reduce inputs as $in ([]; . += [$in|split(",")|. as $a|reduce range(0,length) as $i ({};.[$h[$i]]=$a[$i])])'
@@ -1759,8 +1786,9 @@ function get_ubuntu() {
         zsync_get "${URL}/${ISO}" "${VM_PATH}" "${OS}-devel.iso"
         make_vm_config "${OS}-devel.iso"
     else
-        web_get "${URL}/${ISO}" "${VM_PATH}"
-        check_hash "${ISO}" "${HASH}"
+        echo "Get ISO=${ISO} from cache if possible"
+        cached_web_get $OS $RELEASE "${URL}" "${ISO}" "${VM_PATH}" || return $?
+        check_hash "${ISO}" "${HASH}" || return $?
         make_vm_config "${ISO}"
     fi
 }
